ack-app:
    image: ci-nexus:443/ack/ack:latest
    external_links:
        - ack-postgresql:postgresql
    environment:
        - SPRING_PROFILES_ACTIVE=prod,swagger
        - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/ack
        - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
ack-postgresql:
    extends:
        file: postgresql.yml
        service: ack-postgresql
ack-lb:
    ports:
    - 4242:8080
    labels:
        io.rancher.scheduler.affinity:host_label: name=alex-research
    tty: true
    image: rancher/load-balancer-service
    links:
    - ack-app:ack-app
    stdin_open: true
