ack-postgresql:
    container_name: ack-postgresql
    image: postgres:9.5.4
    volumes:
        - ~/volumes/jhipster/ack/postgresql/:/var/lib/postgresql/
    environment:
        - POSTGRES_USER=ack
        - POSTGRES_PASSWORD=
    ports:
        - 5432:5432
    labels:
            io.rancher.scheduler.affinity:host_label: name=alex-research
